name: kics
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@v3
      # Scan Iac with kics
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
          path: 'terraform,cfn-templates,my-other-sub-folder/Dockerfile'
          output_path: myResults/
      # Display the results in json format
      - name: display kics results
        run: |
          cat myResults/results.json
