name: kics
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@v3
      # Scan Iac with kics
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: 'terraform'
          # when provided with a directory on output_path
          # it will generate the specified reports file named 'results.{extension}'
          # in this example it will generate:
          # - results-dir/results.json
          # - results-dir/results.sarif
          output_path: results-dir
          platform_type: terraform
          output_formats: 'json,sarif'
      - name: Show results
        run: |
          cat results-dir/results.sarif
          cat results-dir/results.json
